AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Swift Application

Globals:
  Function:
    Timeout: 10
    Handler: swift.bootstrap
    Runtime: provided
    MemorySize: 512

Resources:
  SwiftApi: # Match package name in package.swift for Lambda function
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: SwiftApi/
      Events:
        ApiTrigger:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
    Metadata:
      BuildMethod: makefile

  Squared:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Squared/
    Metadata:
      BuildMethod: makefile

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com"