

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: HTTP API -> SQS

Globals:
  Function:
    Timeout: 5
    CodeUri: src/
    Runtime: nodejs12.x

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        openapi: "3.0.1"
        info:
          title: "HTTP-SQS"
          version: "2020-07-23 23:28:39UTC"
        paths:
          /:
            x-amazon-apigateway-any-method:
              responses:
                default:
                  description: "Default response for ANY /"
              x-amazon-apigateway-integration:
                payloadFormatVersion: "1.0"
                type: "http_proxy"
                httpMethod: "ANY"
                uri: !Ref RawQueue
                connectionType: "INTERNET"
        x-amazon-apigateway-importexport-version: "1.0"

  RawQueue:
    Type: AWS::SQS::Queue
  
  RawQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties: 
      PolicyDocument:
        Id: Policy1588221050082
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: '*'
          Action:
          - sqs:SendMessage
          Resource: !GetAtt RawQueue.Arn
      Queues: 
        - !Ref RawQueue

  TriggeredFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt RawQueue.Arn
            BatchSize: 10
            Enabled: true

Outputs:
  RawSqsUrl:
    Description: URL of the SQS Queue
    Value: !Ref RawQueue
  ApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"