openapi: "3.0.1"
info:
  title: "EventBridge DLQ"
paths:
  /eb:
    post:
      responses:
        default:
          description: "EventBridge response"
      x-amazon-apigateway-integration:
        integrationSubtype: "EventBridge-PutEvents"
        credentials:
          Fn::GetAtt: [MyHttpApiRole, Arn]
        requestParameters:
          Detail: "$request.body.Detail"
          DetailType: "MyDetailType"
          Source: "WebApp"
        payloadFormatVersion: "1.0"
        type: "aws_proxy"
        connectionType: "INTERNET"